version: "3.7"

services:
  app:
    container_name: "accountant_bot"
    working_dir: /app
    build:
      dockerfile: ./dockerfile
    env_file:
      - ./.env
    volumes:
      - ./:/app
    command: python3 main.py
